version: '3.2'
services:
  nginx:
    image: richarvey/nginx-php-fpm:latest
    container_name: nginx
    restart: always
    ports:
     - "80:80"
     - "2021:2021" # domain_tool_admin
    volumes:
     - "./nginx/:/etc/nginx"
     - "./nginx/conf.d:/etc/nginx/conf.d"
     - "./nginx/logs:/var/log/nginx"
     - "./webroot/:/var/www/html"
    external_links:
     - mariadb:mariadb
     - phpmyadmin:phpmyadmin
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_sql_root_password
    volumes:
     - "./mariadb/:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    environment:
     - "PMA_HOST=mariadb"
     - "PMA_PORT=3306"
     - "PMA_ABSOLUTE_URI=https://phpmyadmin.your.domain"
    external_links:
     - mariadb:mariadb
    volumes:
     - "./phpmyadmin/sessions:/sessions"